name: Auto Extend FreeGameHost

on:
  schedule:
    - cron: "0 */3 * * *"   # 每 8 小时运行一次
  workflow_dispatch: {}     # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright + Chromium
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Run renew script
        env:
          # AUTO: 先尝试 COOKIE，失败后自动用 EMAIL（默认）
          FG_LOGIN_METHOD: ${{ secrets.FG_LOGIN_METHOD || 'AUTO' }}
          FG_COOKIE: ${{ secrets.FG_COOKIE }}               # 可选（AUTO/COOKIE 时用）
          FG_COOKIE_DOMAIN: panel.freegamehost.xyz
          FG_EMAIL: ${{ secrets.FG_EMAIL }}                 # 可选（AUTO/EMAIL 时用）
          FG_PASSWORD: ${{ secrets.FG_PASSWORD }}           # 可选（AUTO/EMAIL 时用）
          FG_SERVER_KEYWORD: ${{ secrets.FG_SERVER_KEYWORD }}  # 可选，如 "test"
          FG_BASE_URL: https://panel.freegamehost.xyz
          HEADLESS: "true"
          TIMEOUT_MS: "30000"
        run: |
          python renew_freegamehost.py

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
